# DATA
dataset: celeba  # ring8 / grid25 / mnist / fashion_mnist / celeba
dataroot: /home/jason/data
img_size: 64

# MODEL
model_arch: CNN  # MLP / CNN
z_dim: 100

# TRAIN
epochs: 50
batch_size: 256

a: 0
b: 1
c: 1

optimizer:
  choice: adam
  adam:
    lr: 0.0002

d_iters: 1
sample_freq: 1
