# DATA
dataset: mnist  # ring8 / grid25 / mnist
dataroot: /home/jason/data
img_size: 28

# MODEL
z_dim: 100

# TRAIN
epochs: 200
batch_size: 256

optimizer:
  choice: adam
  adam:
    lr: 0.0003

d_iters: 5
sample_freq: 1
