# DATA
dataset: mnist  # ring8 / grid25 / mnist
dataroot: /home/jason/data
img_size: 28

# MODEL
z_dim: 100
ndfs: [256, 256]
ngfs: [256, 256, 256]
nrfs: [256, 256, 256]

# TRAIN
epochs: 200
batch_size: 256

optimizer:
  choice: adam
  adam:
    lr: 0.001
    betas: [0.5, 0.999]

d_iters: 1
sample_freq: 2
