# DATA
dataset: mnist  # ring8 / grid25 / mnist
dataroot: /home/jason/data
img_size: 28

# MODEL
z_dim: 100

# TRAIN
epochs: 300
batch_size: 256

optimizer:
  choice: rmsprop
  rmsprop:
    lr: 0.00005

clip: [-0.01, 0.01]

d_iters: 5
sample_freq: 3
