# DATA
dataset: mnist  # ring8 / grid25 / mnist
dataroot: /home/jason/data
img_size: 28

# MODEL
z_dim: 100

# TRAIN
epochs: 300
batch_size: 256

lambda_gp: 10

optimizer:
  choice: adam
  adam:
    lr: 0.0001
    betas: [0.5, 0.9]

d_iters: 5
sample_freq: 3
