# DATA
dataset: mnist  # mnist / fashion_mnist / celeba
dataroot: /home/jason/data
img_size: 64

# MODEL
z_dim: 100

# TRAIN
epochs: 50
batch_size: 256

optimizerG:
  choice: adam
  adam:
    lr: 0.0001
    betas: [0, 0.9]

optimizerD:
  choice: adam
  adam:
    lr: 0.0004
    betas: [0, 0.9]

d_iters: 1
sample_freq: 1
