# DATA
dataset: mnist  # mnist / fashion_mnist / celeba
dataroot: /home/jason/data
img_size: 64

# MODEL
z_dim: 100

# TRAIN
epochs: 50
batch_size: 512

optimizer:
  choice: adam
  adam:
    lr: 0.0002
    betas: [0.5, 0.999]

d_iters: 1
sample_freq: 1
