seed: 5678

data:
  name: Ring8

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

G:
  target: models.simple_mlp.Generator
  params:
    z_dim: 32
    out_dim: 2
    dim: 256
    dim_mults: [1, 1, 1]
    with_bn: false
    with_tanh: true

D:
  target: models.simple_mlp.Discriminator
  params:
    in_dim: 2
    dim: 256
    dim_mults: [1, 1, 1]
    with_bn: false

train:
  n_steps: 1000
  batch_size: 256
  d_iters: 5
  resume: ~
  print_freq: 100
  save_freq: 1000
  sample_freq: 200
  n_samples: 1000

  loss_fn:
    target: losses.vanilla_gan_loss.VanillaGANLoss
    params: {}

  optim_G:
    target: torch.optim.Adam
    params:
      lr: 0.0003
  optim_D:
    target: torch.optim.Adam
    params:
      lr: 0.0003
