seed: 5678

data:
  name: Ring8

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

G:
  target: models.simple_mlp.Generator
  params:
    z_dim: 32
    out_dim: 2
    dim: 256
    dim_mults: [1, 1, 1]
    with_bn: false
    with_tanh: true

D:
  target: models.simple_mlp.Discriminator
  params:
    in_dim: 2
    dim: 256
    dim_mults: [1, 1, 1]
    with_bn: false
    with_sn: true

train:
  n_steps: 50000
  batch_size: 256
  d_iters: 1
  resume: ~
  print_freq: 500
  save_freq: 10000
  sample_freq: 1000
  n_samples: 1000

  optim_G:
    target: torch.optim.Adam
    params:
      lr: 0.0002
      betas: [0.5, 0.999]
  optim_D:
    target: torch.optim.Adam
    params:
      lr: 0.0002
      betas: [0.5, 0.999]
