seed: 5678

data:
  name: CIFAR-10
  dataroot: /data/CIFAR-10/
  img_size: 32
  img_channels: 3

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

G:
  target: models.simple_cnn.Generator
  params:
    z_dim: 100
    dim: 256
    dim_mults: [4, 2, 1]
    out_dim: 3
    with_bn: true
    with_tanh: true

D:
  target: models.simple_cnn.Discriminator
  params:
    in_dim: 3
    dim: 256
    dim_mults: [1, 2, 4]
    with_bn: true

train:
  n_steps: 200000
  batch_size: 512
  d_iters: 5
  resume: ~
  print_freq: 500
  save_freq: 10000
  sample_freq: 1000
  n_samples: 64

  weight_clip: [-0.01, 0.01]

  optim_G:
    target: torch.optim.RMSprop
    params:
      lr: 0.00005
  optim_D:
    target: torch.optim.RMSprop
    params:
      lr: 0.00005
